# Flutter app
name: balance_app
description: Flutter application to measure you posture!
version: 0.0.1+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  # Flutter main dependencies
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # Bloc dependencies
  flutter_bloc: ^3.2.0
  # Other dependencies
  flutter_svg: ^0.17.1
  quiver: ^2.0.5
  shared_preferences: ^0.5.6+2
  floor: ^0.11.0
  provider: ^4.0.4

dev_dependencies:
  # Test dependencies
  # Unit test dependency
  test: any
  mockito: ^4.1.1
  # Widget test dependency
  flutter_test:
    sdk: flutter
  # Floor dev dependencies
  floor_generator: ^0.11.0
  build_runner: ^1.7.4

flutter:
  uses-material-design: true
  # Assets paths
  assets:
    - assets/icons/