# Flutter app
name: balance_app
description: Flutter application to measure you posture!
version: 0.0.1+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  # Flutter main dependencies
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  path_provider: ^1.6.7

  # Bloc dependencies
  flutter_bloc: ^3.2.0

  # Floor dependencies
  floor: ^0.12.0

  # Provider dependencies
  provider: ^4.0.4

  # Frequency Analysis dependencies
  iirjdart: ^0.0.1
  powerdart: ^0.0.1

  # Miscellaneous dependencies
  flutter_svg: ^0.17.3+1
  quiver: ^2.0.5
  shared_preferences: ^0.5.6+2
  circular_check_box:
    git:
      url: git://github.com/Supercaly/circular_check_box
      ref: development
  custom_dropdown: ^0.0.2
  vibration: ^1.2.4
  audioplayers: ^0.15.1
  charts_flutter: ^0.9.0

dev_dependencies:
  # Test dependencies
  # Unit test dependency
  test: any
  mockito: ^4.1.1

  # Widget test dependency
  flutter_test:
    sdk: flutter

  # Floor dev dependencies
  floor_generator: ^0.12.0
  sqflite_ffi_test:
    git:
      url: git://github.com/tekartik/sqflite_more
      ref: dart2
      path: sqflite_ffi_test

  # Build Runner dependencies
  build_runner: ^1.7.4

flutter:
  uses-material-design: true

  # Assets paths
  assets:
    - assets/logo.png
    - assets/icons/
    - assets/sounds/light_pop.mp3
