/// Flutter icons BIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BIcons
///      fonts:
///       - asset: fonts/BIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BIcons {
  BIcons._();

  static const _kFontFam = 'BIcons';
  static const _kFontPkg = null;

  static const IconData calibration = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_close = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_open = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
